### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by Nash2325138** [Nash2325138/SE_HW2#1]
- [x] Eclipse project source code
  - [x] Grade system source code
  - [x] Test code
  - [x] .ucd file generated from eUML
- [x] User manual
- [x] Acceptance test cases
- [x] Architectural design
- [x] Time allocation(.xlsx file)
  - [x] Unit test cases planning (test code header writing)
  - [x] Unit test coding (test code writing)
  - [x] Pseudo-coding, tracing to debug, and header writing
  - [x] Source coding
  - [x] Unit-testing (including integration)
